server: "hub-cloud.browserstack.com"
user: "fernandacezario1"
key: "i2TZzsjDsjscaRpkVpKq"

common_caps:
  "build": "capybara-browserstack"
  "browserstack.debug": true

browser_caps:
  -
    "browser": "chrome"
  -
    "browser": "firefox"
  -
    "browser": "internet explorer"
  -
    "browser": "safari"
